auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false   # Desactiva OTLP/metadata estructurada
  reject_old_samples: true
  reject_old_samples_max_age: 168h    # 7 días

compactor:
  working_directory: /loki/compactor   # Directorio necesario para compactor

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h               # 7 días

common:
  path_prefix: /loki
