auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  ring:
    kvstore:
      store: consul
      consul:
        host: consul:8500
        http_client_timeout: 20s

ingester:
  lifecycler:
    ring:
      kvstore: {}
      heartbeat_timeout: 1m
    join_after: 0s
  wal:
    enabled: true
    dir: /var/lib/loki/wal

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/boltdb-shipper-active
    cache_location: /var/lib/loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/chunks

compactor:
  working_directory: /var/lib/loki/compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168hv

  query_scheduler:
  max_outstanding_requests_per_tenant: 4096

querier:
  extra_query_delay: 0s
  max_concurrent: 512

frontend:
  max_outstanding_per_tenant: 4096