services:
  postfix:
    build: ./postfix
    container_name: postfix
    hostname: email-threat-docker.local
    ports:
      - "25:25"
    volumes:
      - postfix_logs:/var/log
      - ./postfix/postfix-config/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/postfix-config/master.cf:/etc/postfix/master.cf:ro
      - ./postfix/postfix-config/transport:/etc/postfix/transport:ro
    devices:
      - "/dev/urandom:/dev/random"
    healthcheck:
      test: ["CMD-SHELL", "pgrep master || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      threat-net:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  scanner:
    build:
      context: .
      dockerfile: scanner/Dockerfile
    container_name: scanner
    ports:
      - "10026:10025"
    environment:
      - REINJECTION_HOST=postfix
      - REINJECTION_PORT=10026
      - SCANNER_LISTEN_PORT=10025
    volumes:
      - scanner_logs:/var/log/scanner
      - ./rules:/app/rules:ro
      - quarantine_data:/app/quarantine
    restart: unless-stopped
    networks:
      - threat-net

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - threat-net

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # override via secrets in production
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - threat-net

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - postfix_logs:/logs/postfix:ro
      - scanner_logs:/logs/scanner:ro
      - ./promtail:/etc/promtail
      - positions:/tmp
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - threat-net

volumes:
  postfix_logs:
  scanner_logs:
  quarantine_data:
  loki_data:
  grafana_data:
  positions:

networks:
  threat-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
