services:
  postfix:
    build: ./postfix
    container_name: postfix
    hostname: email-threat-docker.local
    ports:
      - "25:25"
    volumes:
      - ./logs/postfix:/var/log
      - ./postfix/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/master.cf:/etc/postfix/master.cf:ro
      - ./postfix/transport:/etc/postfix/transport:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/urandom:/dev/random"
    healthcheck:
      test: ["CMD-SHELL", "pgrep master || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      threat-net:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  scanner:
    build:
      context: .
      dockerfile: scanner/Dockerfile
    container_name: scanner
    ports:
      - "10026:10025"
    environment:
      - REINJECTION_HOST=postfix
      - REINJECTION_PORT=10026
      - SCANNER_LISTEN_PORT=10025
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./logs/scanner:/var/log
      - ./rules:/app/rules:ro
      - quarantine_data:/app/quarantine
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - threat-net
    
  sigma_scanner:
    build:
      context: .
      dockerfile: sigma_scanner/Dockerfile
    volumes:
      - mail_logs:/var/log
      - ./logs/sigma:/logs/sigma  
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
    networks:
      - threat-net


  loki:
    image: grafana/loki:latest
    container_name: securemail_loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      threat-net:

  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/plugins:/etc/grafana/provisioning/plugins
      - ./grafana/provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password, change in production
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      threat-net:

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      # Mount log volumes from other containers
      - ./logs/postfix:/logs/postfix:ro
      - ./logs/scanner:/logs/scanner:ro
      - ./logs/sigma:/logs/sigma:ro
      - ./promtail:/etc/promtail
      - positions:/tmp # Volume for positions file
      - /etc/localtime:/etc/localtime:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
      - postfix # Ensure log volume exists
      - scanner # Ensure log volume exists
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires 
    networks:
      threat-net:

volumes:
  postfix_logs:
  scanner_logs:
  quarantine_data:
  loki_data:
  grafana_data:
  positions:
  mail_logs:

networks:
  threat-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
