# version: '3.9' Última estable para docker-compose (en el Docker Compose v2, Ya no es necesario especificarlo)

services:

  postfix:
    build: ./postfix
    container_name: postfix
    hostname: email-threat-docker.local
    ports:
      - "25:25"
      - "10026:10026"
    volumes:
      - ./postfix-config/main.cf:/etc/postfix/main.cf:ro
      - ./postfix-config/master.cf:/etc/postfix/master.cf:ro
      - postfix_logs:/var/log
    devices:
      - "/dev/urandom:/dev/random"
    networks:
      threat-net:
        ipv4_address: 172.20.0.100
    restart: unless-stopped

  scanner:
    build: ./scanner
    container_name: scanner
    environment:
      - REINJECTION_HOST=postfix  
      - REINJECTION_PORT=10026
    volumes:
      - scanner_logs:/var/log # Mount log volume
      - ./rules:/app/rules:ro # Mount rules read-only
      - quarantine_data:/app/quarantine # Mount quarantine volume
    depends_on:
      - postfix # Scanner needs postfix to be aware for re-injection, though not strictly required to start
    restart: unless-stopped
    networks:
      threat-net:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: securemail_grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Grafana web UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      threat-net:
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: securemail_loki
    restart: unless-stopped
    ports:
      - "3100:3100" # Loki API
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock  # 🚨 acceso al daemon de Docker
    command: -config.file=/etc/loki/local-config.yml
    networks:
      threat-net:

  promtail:
    image: grafana/promtail:latest
    container_name: securemail_promtail
    restart: unless-stopped
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
    networks:
      threat-net:
    depends_on:
      - loki

volumes:
  grafana_data:
    #driver: local
  scanner_logs:
  postfix_logs:
  quarantine_data:

networks:
  threat-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16