server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: postfix
    static_configs:
      - targets: [localhost]
        labels:
          job: postfix
          __path__: /logs/postfix/mail.log  # Path inside Promtail container

  - job_name: scanner
    static_configs:
      - targets: [localhost]
        labels:
          job: scanner
          __path__: /logs/scanner/mail_scanner.log  # Path inside Promtail container
