server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: postfix
    static_configs:
      - targets: [localhost]
        labels:
          job: postfix
          __path__: /logs/postfix/*.log

  - job_name: scanner
    static_configs:
      - targets:
          - localhost
        labels:
          job: scanner
          __path__: /logs/scanner/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            sender: sender
            recipient: recipient
            subject: subject
            yara_hits: yara_hits
            quarantined: quarantined
      - timestamp:
          source: timestamp
          format: Unix

  - job_name: sigma_scanner
    static_configs:
      - targets: [localhost]
        labels:
          job: sigma_scanner
          __path__: /logs/sigma/*.log
